on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint
        uses: arduino/arduino-lint-action@v1
        with:
          recursive: true
