on: [push, pull_request]
inputs:
  recursive:
    description: "Search path recursively for projects to check."
    required: true
    default: "true"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
